name: CI

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Jenkinsfile Runner
        run: |
          sudo apt-get update && sudo apt-get install -y jenkinsfile-runner
      - name: Check installed dependencies
        run: |
          which jenkinsfile-runner
          jenkinsfile-runner --version
      - name: Run Jenkins pipeline
        run: |
          jenkinsfile-runner -f Jenkinsfile -p BRANCH=${{ github.event.inputs.BRANCH }}
