name: CI

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Jenkinsfile Runner
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          curl -L -o jenkinsfile-runner.tar.gz https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/1.0-alpha-5/jenkinsfile-runner-1.0-alpha-5.tar.gz
          tar -xzvf jenkinsfile-runner.tar.gz
          sudo mv jenkinsfile-runner /usr/local/bin/jenkinsfile-runner
      - name: Check installed dependencies
        run: |
          which jenkinsfile-runner
          jenkinsfile-runner --version
      - name: Run Jenkins pipeline
        run: |
          jenkinsfile-runner -f Jenkinsfile -p BRANCH=${{ github.event.inputs.BRANCH }}
